### ISSUE TITLE
Pagination at click list presents a confusing behaviour

### ISSUE THREAD

**Issue by vmbatlle** [vmbatlle/UrlShortener#11]
Database status:

- 30 clicks registered (from `id = 0` to `id = 29`)
- All clicks between `2020-01-10 20:38:40.16` and `2020-01-10 21:02:27.027`.

Confusing behaviour:

- Accessing `/all` shows all clicks without pagination and WITHOUT ordering.
    - Maybe use `/all` (without query params) as a `page=1` alias.
    - Or else set an automatic redirection from '/all' to '/all?page=1'
- 30 clicks / 5 page_size = 6 pages BUT 7th page appears in the list bellow and when clicked it's EMPTY. Just fix it some how.
- URIs pointing to every page (list bellow table) have by default a `start` query param, eventhough user doesn't input a date themself. Is itreally necessary?
- There is NO form field for selecting _end date_, BUT `end` query param appears always at the URI. There is any clearer alternative?

**Comment by IgnacioSan22** [comment]
URIs pointing to every page (list bellow table) have by default a start query param, eventhough user doesn't input a date themself. Is itreally necessary?
Si no pones siempre valores al cambiar de página si has elegido una ventana temporal se perderá, y buscará sin ventana, por eso por defecto siempre una fecha previa a cualquier posible click por defecto

**Comment by vmbatlle** [comment]
Yes, I can understand that behaviour IN CASE user had input a custom date.
HOWEVER if the user hasn't done so, you shouldn't add that query parameter
by yourself.

Is it possible to implement with an if-statement?

**Comment by IgnacioSan22** [comment]
I think so, I'll try it later
