### ISSUE TITLE
Test: Añadir una URI alcanzable...

### ISSUE THREAD

**Issue by vmbatlle** [vmbatlle/UrlShortener#14]
..., cuya disponibilidad cambia en el tiempo, pasando a no alcanzable, y **viceversa**.

Note: this test is somehow related with #13, but could also be seen as one of the following sequences:

`*create URI* -> [pending validation] -> URI -> *URI unreachable * -> [invalid] -> *(retry) URI reachable* -> [valid]`

`*create URI* -> [pending validation] -> URI -> *URI reachable* -> [valid] -> *(recheck) URI unreachable* -> [invalid]`

or any combination of the previous sequences that the developer considers (more) interesting.

**Comment by JaviBite** [comment]
Ya va
